### ISSUE TITLE
usage confusion

### ISSUE THREAD

**Issue by despairblue** [electronjs/electron-rebuild#14]
I have a package that is listed as not compatible with atom under linux (the warning does not appear on osx, which is weird, but another issue):

```
Atom Mermaid 0.1.1
Listed below are the incompatible native modules that this package depends on.

contextify@0.1.14
Error message: Module did not self-register.
```

So I try to fix this with:
```
$ cd ~/.atom/packages/atom-mermaid
$ npm install --save-dev electron-rebuild
$ ./node_modules/.bin/electron-rebuild -v 0.22.3 -m node_modules/
Couldn't find electron-prebuilt and no --node-module-version parameter set, always rebuilding
```

This message is kind of confusing. What node module version is it talking about? atom-mermaid's? contextify's?
It still does something, but the incompatibility message did not disappear.

Trying this
```
$ ./node_modules/.bin/electron-rebuild -v 0.22.3 -m node_modules/ -n 0.1.1 # atom-mermaids version
```

It still does something, but the incompatibility message did not disappear.

```
$ ./node_modules/.bin/electron-rebuild -v 0.22.3 -m node_modules/d3/node_modules/jsdom/node_modules/contextify/ -n 0.1.14
```

The incompatibility message did not disappear.

Am I missing anything? Choosing `-m` and `-n` is complete guess work for me :confused:

**Comment by despairblue** [comment]
Tried this as well, to no avail:
```
$ cd node_modules/d3/node_modules/jsdom/node_modules/contextify/
$ npm install --save-dev electron-rebuild
$ ./node_modules/.bin/electron-rebuild -v 0.22.3  -n 0.1.14
```

**Comment by paulcbetts** [comment]
Atom the text editor doesn't use `electron-rebuild`, you probably want the `apm rebuild` command

**Comment by despairblue** [comment]
@paulcbetts nope, since `apm rebuild` does not work. 

For reference:
* [this is the package in question](https://github.com/y-takey/atom-mermaid/issues/5)
* [this is an atom issue that specifically (well, following the linked issue to the electron wiki) points to this tool in the case of npm packages that use prebuild binaries, I don't don't know if that's the case for contextify, but it seemed worth a shot](https://github.com/atom/atom/issues/5158)

A little explanation of the command line options would be appreciated. :pray:
