### ISSUE TITLE
error, Unexpected token case. (windows)

### ISSUE THREAD

**Issue by Riuujin** [electronjs/electron-rebuild#22]
I am trying to use electron rebuild on windows (10 , x64), running node 4.1.0. But when I run the command specified in the documentation 
>./node_modules/.bin/electron-rebuild

I get the following error

>F:\app\node_modules\.bin\electron-rebuild:4
>case `uname` in
>^^^^
>
>SyntaxError: Unexpected token case
>    at exports.runInThisContext (vm.js:53:16)
 >   at Module._compile (module.js:413:25)
>    at Object.Module._extensions..js (module.js:452:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Function.Module.runMain (module.js:475:10)
>    at startup (node.js:117:18)
>    at node.js:951:3

**Comment by paulcbetts** [comment]
`node .\node_modules\.bin\electron-rebuild`

**Comment by Riuujin** [comment]
Oke, thank you.

**Comment by Riuujin** [comment]
Still getting the same error.

**Comment by wiziple** [comment]
Is there anyone solve this issue? I am getting same error on Windows. node js 4, electron 0.33

**Comment by xiemeilong** [comment]
I have the same issue.

**Comment by MattiooFR** [comment]
I'm having the same issue, does someone succeed getting trough this ?

**Comment by RolandHemmer** [comment]
Hi,
I have the same issue too.
I'm trying to compress JS files in a Symfony application using UglifyJS.

Any news ?

**Comment by MattiooFR** [comment]
Using the node-gyp way : https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-node-gyp-way, rebuilding your module for electron works !

**Comment by alexandrubau** [comment]
I have the same issue on Windows. Could you please translate the "node-gyp" way for Windows ? Thanks

**Comment by paulcbetts** [comment]
Oops, there was a typo, it should just be:

```cmd
.\node_modules\.bin\electron-rebuild
```

**Comment by alexandrubau** [comment]
I am trying to compile `cap` ( https://github.com/mscdex/cap ) on Windows7 x32 using
`node .\node_modules\.bin\electron-rebuild` as described in Electron's documentation but I get this error:

![screen](https://cloud.githubusercontent.com/assets/1225661/10679258/16e27c1e-7920-11e5-9fe8-ec6cca4ba95e.png)

**Comment by paulcbetts** [comment]
@alexandrubau Drop the `node` from the front

**Comment by alexandrubau** [comment]
It worked ! Thank you so much ! It should be better if it was specified in the docs. For Windows to run without the front `node`.

Thanks again, have a nice day !

**Comment by surysharma** [comment]
Thanks @paulcbetts got it working but I have to escape the backslash. So this one worked for me.
`.\\node_modules\\.bin\\supervisor`
