### ISSUE TITLE
Unsupported target version: 0.34.0

### ISSUE THREAD

**Issue by domingosl** [electronjs/electron-rebuild#31]
Upon rebuilding npm serialport using electron-rebuild, im getting the error: "Unsupported target version: 0.34.0":

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.34.0
node-pre-gyp ERR! stack     at get_node_abi (/home/domingo/dev/hookninja/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:27:19)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/domingo/dev/hookninja/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:133:21)
node-pre-gyp ERR! stack     at install (/home/domingo/dev/hookninja/node_modules/serialport/node_modules/node-pre-gyp/lib/install.js:134:35)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/domingo/dev/hookninja/node_modules/serialport/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/home/domingo/dev/hookninja/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:77:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/domingo/dev/hookninja/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:130:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 3.19.0-25-generic
node-pre-gyp ERR! command "node" "/home/domingo/dev/hookninja/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/domingo/dev/hookninja/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.37
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok 
Unsupported target version: 0.34.0

npm ERR! serialport@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.0.1 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "serialport"
npm ERR! cwd /home/domingo/dev/hookninja
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by paulcbetts** [comment]
Update node-pre-gyp to the latest version, if that doesn't work then serialport needs to update their canned version of node-pre-gyp
