### ISSUE TITLE
Failed to check Electron's module version number

### ISSUE THREAD

**Issue by adrian-nicolau** [electronjs/electron-rebuild#37]
On Windows:
```
> .\node_modules\.bin\electron-rebuild.cmd
46
Failed to check Electron's module version number: [...]
```
electron-prebuilt and electron-rebuild were both installed with `npm install --save-dev`:
```
"devDependencies": {
    "electron-prebuilt": "^0.35.2",
    "electron-rebuild": "^1.0.2"
}
```

**Comment by adrian-nicolau** [comment]
It seems that w/ electron-prebuilt 0.35.2, line
`versionAsString = (result.stdout + result.stderr).replace(/\n/g, '');`
leads to an empty version string.
Manually setting `versionAsString = '46'` solved the problem.

My guess is that electron.exe's std(out|err) is not forwarded to electron-rebuild, but printed straight to the console (46 in the log above).

**Comment by timfish** [comment]
I'm getting this on Windows too. Does this need filing in the electron repo?

**Comment by dvlsg** [comment]
I am also having this issue on Windows, and can confirm that `result.stdout` and `result.stderr` are both empty strings inside the `getElectronModuleVersion` method.

**Comment by felicienfrancois** [comment]
I get the same issue, when rebuilding electron 32bit from a windows 8.1 32bit box.
Rebuilding electron 64bit  from a 32bit box works, and building both of it from windows 10 64bit works.

Tested with electron-prebuilt 0.35.4 installed as devDependencies

**Comment by paulcbetts** [comment]
Gonna try to fix this soonish, sorry about the bug

**Comment by dvlsg** [comment]
No worries, thanks for keeping an eye on it! This project definitely makes my build process simpler.

**Comment by black-snow** [comment]
I am trying to `electron-rebuild` but it fails. After settings `versionAsString = '46'` in `lib/main.js:124` I got further. But now I'm facing another issue:

> npm WARN prefer global npm@2.14.15 should be installed with -g
gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\developer\Desktop\EPS\node_modules\nslog\build\Release\nslog.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\developer\\Desktop\\EPS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\developer\Desktop\EPS\node_modules\nslog
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by black-snow** [comment]
Hah, after deleting that file manually it worked. Anyhow, please fix the original issue :)

**Comment by felicienfrancois** [comment]
A quick fix is to set the `ELECTRON_NO_ATTACH_CONSOLE` environnement variable to 1 when rebuilding.
In cmd:
```
SET ELECTRON_NO_ATTACH_CONSOLE=1 && node_modules\.bin\electron-rebuild
```

In shell
```
ELECTRON_NO_ATTACH_CONSOLE=1 node_modules/.bin/electron-rebuild
```

I made a pull request a few weeks ago to fix the issue. Waiting for merge.

**Comment by black-snow** [comment]
@felicienfrancois This indeed fixed it, thank you very much.
Line 14 in *rebuild.js* now looks like this (for me, on windows):

```javascript
return promisedExec('SET ELECTRON_NO_ATTACH_CONSOLE=1 && ' + electron + ' --version')
```

**Comment by felicienfrancois** [comment]
This happen systematically when using a UNIX shell emulator (MinGW & co)
