### ISSUE TITLE
Rebuild exits fine / cannot find module 'express'

### ISSUE THREAD

**Issue by black-snow** [electronjs/electron-rebuild#38]
I tried taking the ["easy way"](http://electron.atom.io/docs/v0.35.0/tutorial/using-native-node-modules/#the-easy-way) to include express into my electron project. Sadly it's still throwing me a `Cannot find module 'express'`.

What I did:

1) `npm install --save-dev electron-rebuild`
2) `npm install --save-dev electron-prebuilt`
3) `npm install --save express`
4) `.\node_modules\.bin\electron-rebuild.cmd` (yes, I'm on Windows)
5) Run my project (`var express = require('express');`)

No errors, filemtime updated, no idea what I'm doing wrong. Any clue?

**Comment by paulcbetts** [comment]
express doesn't need native modules, I'm not sure that this is related (the Windows part is fine). What's your full project structure look like and how are you starting your app?

Also, as an aside, unless you really really really need to, the "Start a local webserver" thing is an antipattern in Electron - you should just use files instead.

**Comment by black-snow** [comment]
![electron](https://cloud.githubusercontent.com/assets/579733/11671736/ac91a334-9e0a-11e5-918c-eb861d5db91b.png)
![modules](https://cloud.githubusercontent.com/assets/579733/11671741/af4e527a-9e0a-11e5-8182-3d8281b91a34.png)

It looks like this. `resources` contains a directory `app` that contains my stuff.
How do I use express with electron? I'm pretty new to node and absolutely new to electron.

I really, really need to start a local webserver for it's pretty much what my app is supposed to do (plus some settings and starting some services). (What do you mean by "just use files instead"?)

PS: Thanks for the reply!

**Comment by paulcbetts** [comment]
Your node_modules folder needs to be inside resources

>  (What do you mean by "just use files instead"?)

I mean, many people try to spin up a local HTTP server, then navigate Electron to it in order to serve up their own app. This is a bad (but common :-/) approach. Instead, you should just use file:// URLs everywhere and run the local content that is in resources

**Comment by black-snow** [comment]
Haha, that was easy. Thanks
