### ISSUE TITLE
spawn dist/electron.exe ENOENT

### ISSUE THREAD

**Issue by builden** [electronjs/electron-rebuild#39]
win10 + 64
node.js 5.1.1 + 32
```json
  "dependencies": {
    "ffi": "^2.0.0"
  },
  "devDependencies": {
    "electron-prebuilt": "^0.36.0",
    "electron-rebuild": "^1.0.2"
  }
```
* exec
```bash
.\node_modules\.bin\electron-rebuild.cmd
```
* error info
```bash
spawn dist/electron.exe ENOENT
Error: spawn dist/electron.exe ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

node_modules\electron-prebuilt\dist\electron.exe is exist

**Comment by rspieker** [comment]
I had a similar problem on OSX (same error, different executable of course).
OSX 10.10.5 / OSX 10.11.1
Node.js 5.0.0 / 5.1.0

Worked around it by changing `node_modules/electron-rebuild/lib/spawn.js`

Around line 25, there is this code:
```
  return new _Promise(function (resolve, reject) {
    var error = null;
    //console.log("Calling spawn! " + JSON.stringify(options));
    var proc = _child_process2['default'].spawn(options.cmd, options.args, options.opts);
```

Changed it to provide the `cwd` (current working directory) to the spawn command
```
  return new _Promise(function (resolve, reject) {
    var error = null;
    if (!('cwd' in options.opts)) {
        options.opts.cwd = process.cwd() + '/node_modules/electron-prebuilt';
    }
    //console.log("Calling spawn! " + JSON.stringify(options));
    var proc = _child_process2['default'].spawn(options.cmd, options.args, options.opts);
```

I'm sure this isn't the way to go (as the paths on various OS's will differ), hence I haven't made a pull request.

**Comment by dziudek** [comment]
@rspieker - thank you for your advice - for me your fix is working :+1:

**Comment by builden** [comment]
switch to npm 2 can temporary solution to the problem

**Comment by stevedekorte** [comment]
Tried this change and am getting:

Cannot find module 'npm/node_modules/node-gyp/bin/node-gyp'
Error: Cannot find module 'npm/node_modules/node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.require.resolve (module.js:389:19)
    at installNodeHeaders$ (/Users/steve/Desktop/electron/node_modules/electron-rebuild/lib/main.js:166:25)
    at tryCatch (/Users/steve/Desktop/electron/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/steve/Desktop/electron/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/steve/Desktop/electron/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/steve/Desktop/electron/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/Users/steve/Desktop/electron/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /Users/steve/Desktop/electron/node_modules/babel-runtime/regenerator/runtime.js:156:13
    at run (/Users/steve/Desktop/electron/node_modules/core-js/library/modules/es6.promise.js:104:47)

with node v5.1.1 and npm 3.3.12

**Comment by ConnorGBrewster** [comment]
I am having the same issue as @stevedekorte. Installing node-gyp also did not fix the issue for me.

**Comment by develar** [comment]
BTW, I realized that only 15 lines of code is required to build native modules — https://github.com/develar/onshape-desktop-shell/blob/master/build/util.js#L12-L27

**Comment by stevedekorte** [comment]
I was able to resolve my problem by doing a complete removal and re-install of node/npm.

**Comment by jg123** [comment]
@stevedekorte What steps did you take to remove and reinstall? Did you reinstall node 5.3? I have uninstalled/reinstalled using brew and nvm and am still getting the same error as above.

**Comment by felicienfrancois** [comment]
Sometimes, electron_prebuilt is not installed correctly and the path.txt file is not updated correctly fix the full absolute path but with the relative path.

A quick fix is to either clean npm cache and reinstall electron-prebuilt or to update path.txt with the absolute path.

The normal fix is to makes electron-rebuild works also with relative path. I made a pull request

**Comment by ConnorGBrewster** [comment]
Reinstalling electron_prebuilt, clearing the npm cache, and setting the absolute path in path.txt fixed the issue for me, thanks for the help!

**Comment by aggregatejeff** [comment]
Thank you @rspieker. Worked for me too

**Comment by tomprogers** [comment]
No combination of reinstalling, clearing npm's cache, or editing the path.txt file work for me.

MacOS 10.11.3
npm 2.14.12
node 4.2.6
electron-prebuilt 0.36.4

My path.txt file contains:

```
dist/Electron.app/Contents/MacOS/Electron
```

I've tried modifying that to an absolute path:

```
/Users/tom/projects/xde/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
```

And to a project-relative path:

```
./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
```

But electron-prebuilt throws a fatal error at startup unless I use the original path. Here's the error:

```
{ [Error: Command failed: /bin/sh -c npm start
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/tom/projects/xde/node_modules/electron-prebuilt/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by stevedekorte** [comment]
You might want to make sure you wipe any bash or shell path references to node/npm as well.

**Comment by paulcbetts** [comment]
@tomprogers I don't think this is a bug related to electron-rebuild

**Comment by felicienfrancois** [comment]
@tomprogers 
> But electron-prebuilt throws a fatal error at startup __unless I use the original path__

Why don't you use the original path ?
