### ISSUE TITLE
rebuild fails silent on Windows 10; node 4.2.2; node-gyp 3.0.3

### ISSUE THREAD

**Issue by s-a** [electronjs/electron-rebuild#42]
I tried to compile node-sass with your example code in the readme. 

    var version = "0.36.1";
    var targetFolder = "c:/git/require";
    var path = require("path");
    var targetFolderNodeModulesFolder = path.join(targetFolder, 'node_modules');
    var rebuild = require("electron-rebuild");
    
    
    var rebuildNativeModules = function() {
    	console.log("rebuildNativeModules");
    	return rebuild.rebuildNativeModules(version, targetFolderNodeModulesFolder);
    };
    
    var installNodeHeaders = function (shouldBuild) {
    	console.log("installNodeHeaders", shouldBuild);
    	if (!shouldBuild) return true;
    	return rebuild.installNodeHeaders(version).then(rebuildNativeModules);
    }
    
    var error = function  (e) {
    	console.log("error");
    	console.error("Building modules didn't work!");
    	console.error(e);
    }
    
    rebuild.shouldRebuildNativeModules(targetFolder).then(installNodeHeaders).catch(error);}

 I also tried 
```electron-rebuild --version 0.36.1 --module-dir c:\git\require\node_modules``` without success.

**Comment by paulcbetts** [comment]
node-sass does some odd frustrating things that make it incompatible with electron-rebuild or any other solution for building node modules with Electron, sorry :(
