### ISSUE TITLE
node-gyp error when running rebuild on node usb

### ISSUE THREAD

**Issue by stellasoft-will** [electronjs/electron-rebuild#43]
i need to run a node-gyp rebuild on node usb as electron rebuild does not work because of node-pre-gyp, i have run the following guys advice on mac osx and it works perfectly, but windows it fails (running windows 10 with vs 2015 community desktop).

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\matthewhardern\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\matthewhardern\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.36.2" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\electron-test\node_modules\usb
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

following this https://discuss.atom.io/t/use-node-usb-inside-electron/16748/2

third comment down.

any help would be great.

**Comment by armaseg** [comment]
Hello @stellasoft-will !
I had the same problem, can you try to use Visual Studio 2013 Express R5 ?
Regards,

**Comment by stellasoft-will** [comment]
thanks very much you saved me on a project there. closing issue using visual studio 2013 fixes issue.
