### ISSUE TITLE
mention require-rebuild

### ISSUE THREAD

**Issue by juliangruber** [electronjs/electron-rebuild#49]
I wrote a module for this that takes a different approach: it patches `require()` to recompile node modules on the fly if they have been built against a different api. More magic, but one step less to worry about.

https://github.com/juliangruber/require-rebuild

Might be nice to mention in the README. Feel free to just close and ignore if you think otherwise.

**Comment by paulcbetts** [comment]
Huh, very clever. Send me a PR and I'll add it

**Comment by havenchyk** [comment]
@juliangruber hmm. Doesn't work for me in my electron application.

**Comment by juliangruber** [comment]
@paulcbetts sure, will do!
@havenchyk oops, please open an issue on https://github.com/juliangruber/require-rebuild/issues/new with your exact error
