### ISSUE TITLE
Node-sass bindings

### ISSUE THREAD

**Issue by stefanKuijers** [electronjs/electron-rebuild#55]
I would like to make an electron app which can compile sass for you using node-sass. I packaged the app (from Linux) but once I open the app on Windows it sass the bindings are not found and I should rebuild. 
```` Error: `libsass` bindings not found. Try reinstalling `node-sass` ````
I dropped in a precompiled file from the [node-sass-binaries](https://github.com/sass/node-sass-binaries) but I get an error about dynamic links. 

Is electron-build a package which can handle this kind of problem? if not; where should I look? 
I want anyone on WIN, Linux and OSX to just install my app and compile sass.

**Comment by Paxa** [comment]
What you want is cross-compilation. I think npm can not do it, you may try compile your dependencies on windows and mac. I think you can use cloud hosting for that

**Comment by stefanKuijers** [comment]
So we can run ````npm rebuild node-sass```` within the electron environment to accomplish this?

I would assume this gives me exactly the same result as dropping in a precompiled binary from the repo I linked to. But I could be wrong.

I would assume this is specific to electron. [I found this issue on it](https://github.com/sass/node-sass/issues/1047) which led me to think it might be better to ask it here.

**Comment by paulcbetts** [comment]
node-sass uses node-pre-gyp which is notoriously problematic with Electron. People have tried to fix it but nobody will merge the PR to do it

**Comment by stefanKuijers** [comment]
@Paxa Do you have a PaaS which could be used for this? If I understand right this would mean that I would build the app on each platform for that platform. eg: build for OSX on OSX, build on Windows for Windows etc.

**Comment by stefanKuijers** [comment]
@paulcbetts which PR is nor merged in yet? could you link to it? Cause I checked some PRs which already have been merged but if I understand right they are not valid anymore.

**Comment by Paxa** [comment]
Yes, but I don't know what PaaS you can use for that. May be at first you can try to use virtual machines with OSX and Windows (e.g. VirtualBox)

**Comment by stefanKuijers** [comment]
I will try this soon. Thank you very much for suggestions. 

@Paxa would you be interested to solve this problem also or are you just helping out where you can?

**Comment by stefanKuijers** [comment]
Got it working with a slight variation to the rebuild instructions as suggested by [this answer](https://discuss.atom.io/t/cross-platform-sass-compilation-with-node-sass-libsass/26372).
